packages:
  - "apps/*"
  - "packages/*"

disallowWorkspaceCycles: true

catalog:
  typescript: ^6.0.3
  vitest: ^4.1.10
  "@vitest/coverage-istanbul": ^4.1.10
  zod: ^4.4.3

allowBuilds:
  "@scarf/scarf": true
  "@swc/core": true
  cpu-features: true
  esbuild: true
  protobufjs: true
  ssh2: true
